ckpt_path: "/home/simeon/GitRepositories/ml_coarsening/important_models/2026-01-21_passionate_otter_900/checkpoints/epoch_015.ckpt"
model_class: "MLCoarseningModule"
output_dir: "./exported_model/passionate_otter_900"