run_name: ""

defaults:
  - _self_
  - data: pred_default  # Fixed the path format
  - trainer: default
  - paths: default
  - debug: null
  - hydra: default
  - experiment: null

task_name: "inference"
model_dir: ${paths.root_dir}/logs/train/runs/2025-05-30_12-17-44/
ckpt_path: ${model_dir}checkpoints/epoch_060.ckpt
metis_path: /nfs/work/students/ml_coarsening/graph_metis_files/
model_class: "BinaryClassificationModule"
flags: ""
# Training-specific parameters
seed: 42

